- samples/17.multilingual-bot/src/main/resources/application.properties
> [17.multilingual-bot] Add application.properties

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/translation/TranslationSettings.java
> [17.multilanguage-bot] Add TranslationSettings class

- samples/17.multilingual-bot/deploymentTemplates/new-rg-parameters.json
- samples/17.multilingual-bot/deploymentTemplates/preexisting-rg-parameters.json
- samples/17.multilingual-bot/deploymentTemplates/template-with-new-rg.json
- samples/17.multilingual-bot/deploymentTemplates/template-with-preexisting-rg.json
> [17.multilingual-bot] Migrate DeploymentTemplates folder

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/Application.java
> [17.multilanguage-bot] Add Application.java

- samples/17.multilingual-bot/LICENSE
- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/Application.java
> [17.multilingual-bot] Add License and TranslatorMiddleware in Application

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/translation/model/TranslationResult.java
> [17.multilingual-bot] Add TranslationResult class

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/translation/model/TranslationResponse.java
> [17.multilingual-bot] Add TranslationResponse class

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/Application.java
> [17.multilingual-bot] Update application.java

- samples/17.multilingual-bot/README.md
> [17.multilingual-bot] Add README

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/translation/TranslationMiddleware.java
> [17.multilingual-bot] Add TranslationMiddleware

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/MultiLingualBot.java
> [17.multilingual-bot] Add MultiLingualBot class

- libraries/bot-ai-qna/README.md
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai-qna/dialogs/QnAMakerDialog.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai-qna/models/FeedbackRecord.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai-qna/utils/ActiveLearningUtils.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/dialogs/QnAMakerDialogTest.java
> [bot-ai-qna] Create main structure for the library

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/translation/MicrosoftTranslator.java
> [17.multilingual-bot] Add MicrosoftTranslator class

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QnARequestContext.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QnAResponseContext.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QueryResult.java
> [Bot-Ai-Qna] Add QnARequestContext, QnAResponseContext and QueryResult files

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/FeedbackRecord.java
> [Bot-Ai-Qna] Add FeedbackRecord

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/FeedbackRecords.java
> [Bot-Ai-Qna] Add FeedbackRecords.java

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/Metadata.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QnAMakerTraceInfo.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QueryResults.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/RankerTypes.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/schemas/Microsoft.QnAMakerRecognizer.schema
> [Bot-Ai-QnA] Add Metadata, QnAMakerTraceInfo, QueryResults, RankerTypes and schemas

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/ActiveLearningUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/BindToActivity.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/QnACardBuilder.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/QnATelemetryConstants.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/TrainUtils.java
> [Bot-Ai-QnA] Add ActiveLearningUtils, BindToActivity and QnATelemetryConstant

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/MultiLingualBot.java
> [17.multilingual-bot] Applying feedback to fix targeting only the first non target

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/IQnAMakerClient.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/TrainUtils.java
> [Bot-Ai-QnA] Add more utils

- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/Application.java
- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/MultiLingualBot.java
- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/translation/MicrosoftTranslator.java
- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/translation/TranslationMiddleware.java
- samples/17.multilingual-bot/src/main/java/com/microsoft/bot/sample/multilingual/translation/model/TranslatorResponse.java
> [17.multilingual-bot] Fix test errors

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/ITelemetryQnAMaker.java
> [Bot-Ai-QnA] Add ITelemetryQnAMaker interface

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerDialog.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerDialogOptions.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerPrompt.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/FeedbackRecord.java
> [Bot-Ai-QnA] Add dialogs folder

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/JoinOperator.java
> [Bot-Ai-QnA] Add JoinOperator enum

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnADialogResponseOptions.java
> [Bot-Ai-QnA] Add QnADialogResponseOptions class

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerEndpoint.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
> [Bot-Ai-QnA] Add QnAMakerRecognizer class

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/IQnAMakerClient.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/ITelemetryQnAMaker.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnADialogResponseOptions.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMaker.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerComponentRegistration.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerEndpoint.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerOptions.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerDialog.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerDialogOptions.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/dialogs/QnAMakerPrompt.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/FeedbackRecord.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/FeedbackRecords.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/Metadata.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QnAMakerTraceInfo.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QnARequestContext.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QnAResponseContext.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QueryResult.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/QueryResults.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/models/RankerTypes.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/ActiveLearningUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/BindToActivity.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/QnACardBuilder.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/QnATelemetryConstants.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/TrainUtils.java
> [Bot-Ai-QnA] Apply fixes

- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai-qna/QnAMakerTraceInfoTests.java
> [QnA] Add QnAMakerTraceInfoTests

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerOptions.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
> [QnA] Add QnAMakerRecognizer, QnAMakerRecognizerTests and fix issues

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMaker.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTraceInfoTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/adapters/TestAdapter.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/ObjectPath.java
> [QnA] Fix QnAMakerRecognizerTests unit tests

- libraries/bot-ai-qna/pom.xml
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMaker.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/HttpRequestUtils.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTraceInfoTests.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/testData/QnaMaker_ReturnsAnswer_GivenScoreThresholdQueryOption.json
> [QnA] Fix QnA unit tests

- samples/11.qnamaker/LICENSE
- samples/11.qnamaker/README.md
- samples/11.qnamaker/deploymentTemplates/template-with-new-rg.json
- samples/11.qnamaker/deploymentTemplates/template-with-preexisting-rg.json
- samples/11.qnamaker/src/main/java/com/microsoft/bot/sample/qnamaker/Application.java
- samples/11.qnamaker/src/test/java/com/microsoft/bot/sample/qnamaker/ApplicationTest.java
> [Samples][11.qnamaker] Add project structure

- samples/11.qnamaker/deploymentTemplates/new-rg-parameters.json
- samples/11.qnamaker/deploymentTemplates/preexisting-rg-parameters.json
- samples/11.qnamaker/deploymentTemplates/template-with-new-rg.json
- samples/11.qnamaker/deploymentTemplates/template-with-preexisting-rg.json
> [Samples][11.qnamaker] Add deploymentTemplates folder

- samples/11.qnamaker/src/main/webapp/META-INF/MANIFEST.MF
- samples/11.qnamaker/src/main/webapp/WEB-INF/web.xml
- samples/11.qnamaker/src/main/webapp/index.html
> [Samples][11.qnamaker] Add webapp folder

- samples/11.qnamaker/src/main/resources/application.properties
- samples/11.qnamaker/src/main/resources/log4j2.json
> [Samples][11.qnamaker] Add application.properties

- samples/11.qnamaker/pom.xml
- samples/11.qnamaker/src/main/java/com/microsoft/bot/sample/qnamaker/QnABot.java
> [Samples][11.qnamaker] Add qnabot class

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbKeyEscape.java
> [Bot-Azure] Update CosmosDbKeyEscape

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbPartitionedStorageOptions.java
> [Bot-Azure] Update CosmosDbPartitionedStorageOptions

- samples/11.qnamaker/src/main/java/com/microsoft/bot/sample/qnamaker/Application.java
> [Samples][11.qnamaker] Add Application class

- samples/11.qnamaker/src/main/resources/smartLightFAQ.tsv
> Add smartLightFAQ file to project

- samples/11.qnamaker/README.md
> [Samples][11.qnamaker] Add README

- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/CosmosDBKeyEscapeTests.java
> [Bot Azure] Update CosmosDBKeyEscapeTests

- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/CosmosDbPartitionStorageTests.java
> [Bot Azure] Update CosmosDbPartitionStorageTests

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbKeyEscape.java
- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbPartitionedStorage.java
- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbPartitionedStorageOptions.java
> [Bot Azure] Fix tests

- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/Application.java
> [Samples][13.core-bot] Add Application.java class

- samples/13.core-bot/src/main/resources/application.properties
- samples/13.core-bot/src/main/resources/log4j2.json
> Add Application.properties

- samples/13.core-bot/pom.xml
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/DialogBot.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/package-info.java
> Add DialogBot class and POM

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/queues/AzureQueueStorage.java
- libraries/bot-builder/pom.xml
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/QueueStorage.java
> [SDK][Bot-Azure] Implements AzureQueueStorage

- libraries/bot-azure/pom.xml
- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/AzureQueueTests.java
- libraries/bot-builder/pom.xml
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ActivityEventNames.java
> [SDK][Bot-Azure] Add AzureQueueTests

- samples/13.core-bot/src/main/webapp/META-INF/MANIFEST.MF
- samples/13.core-bot/src/main/webapp/WEB-INF/web.xml
- samples/13.core-bot/src/main/webapp/index.html
> [Samples][13.core-bot] Add webapp folder

- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/CancelAndHelpDialog.java
> Add CancelAndHelpDialog class

- samples/13.core-bot/cognitiveModels/FlightBooking.json
> [Samples][13.core-bot] Add cognitiveModels

- samples/13.core-bot/README-LUIS.md
- samples/13.core-bot/README.md
- samples/13.core-bot/pom.xml
> [Samples][Core-Bot] Add READMEs

- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/BookingDetails.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/FlightBookingRecognizer.java
> [Samples][Core-Bot] Add BookingDetails and FlightBookingRecognizer

- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/Application.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/BookingDialog.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/FlightBookingRecognizer.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/MainDialog.java
> [Samples][Core-Bot] Add MainDialog class

- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/BookingDialog.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/DateResolverDialog.java
> [Samples][13.core-bot] Add BookingDialog and DateResolver classes

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/queues/AzureQueueStorage.java
- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/queues/package-info.java
- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/AzureQueueTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/adapters/TestAdapter.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/prompts/ConfirmPromptLocTests.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ActivityEventNames.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ConversationReference.java
> [SDK] [Bot-Azure] Fix several issues

- samples/13.core-bot/pom.xml
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/Application.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/BookingDetails.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/BookingDialog.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/CancelAndHelpDialog.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/DateResolverDialog.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/DialogAndWelcomeBot.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/DialogBot.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/FlightBookingRecognizer.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/MainDialog.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/package-info.java
- samples/13.core-bot/src/main/resources/application.properties
> [Samples][13.core-bot] Fix the migration issues

- samples/25.message-reaction/pom.xml
> Add main structure

- samples/25.message-reaction/deploymentTemplates/template-with-new-rg.json
- samples/25.message-reaction/deploymentTemplates/template-with-preexisting-rg.json
> Add deployment templates to deploymentTemplates folder

- samples/25.message-reaction/src/main/resources/application.properties
> [Samples][25.message-reaction] Migrate Properties folder

- samples/25.message-reaction/src/main/webapp/META-INF/MANIFEST.MF
- samples/25.message-reaction/src/main/webapp/WEB-INF/web.xml
- samples/25.message-reaction/src/main/webapp/index.html
> [Samples][25.message-reaction] Add webapp

- samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/Application.java
> Add Application class

- samples/25.message-reaction/src/main/resources/application.properties
> Add values from appsettings.json

- samples/25.message-reaction/README.md
> Add readme file

- samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/ActivityLog.java
- samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/activityLog.java
> [Samples][25.message-reaction] Add activityLog class

- libraries/bot-azure/pom.xml
- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/blobs/BlobsTranscriptStore.java
> [SDK] [Bot Azure] BlobsTranscriptStore

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/blobs/BlobsStorage.java
- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/TranscriptStoreTests.java
- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/blobs/BlobsStorageTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/StorageBaseTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TestPocoState.java
> [SDK][Bot Azure] Create BlobsStorage

- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/Activity.java
- samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/ActivityLog.java
- samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/Application.java
- samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/MessageReactionBot.java
- samples/25.message-reaction/src/main/java/com/microsoft/bot/sample/messagereaction/package-info.java
> [Samples][25.message-reaction] Fix sample

- libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/core/TelemetryInitializerMiddleware.java
- libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/core/package-info.java
> [SDK app-insights] Add TelemetryInitializerMiddleware class

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/blobs/BlobsTranscriptStore.java
- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/TranscriptStoreTests.java
- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/blobs/BlobsStorageTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TranscriptMiddlewareTest.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/Activity.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/NanoClockHelper.java
> [SDK][BlobsStorage] Fix BlobsTranscriptStore class & unit tests

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/blobs/BlobsStorage.java
- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/blobs/BlobsStorageTests.java
> [SDK][BlobsStorage]Fix BlobsStorage class & unit tests

- libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/TelemetryWaterfallTests.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/WaterfallDialog.java
> [SDK][ApplicationInsights] Implement tests

- libraries/bot-applicationinsights/pom.xml
- libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/TelemetryInitializerTests.java
> [SDK][Application-Insights] Telemetry Initializer Tests

- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/blobs/BlobsStorageTests.java
> [SDK][Bot-Azure] Replace assertEmulator with runIfEmulator

- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/QnAMakerRecognizer.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/GenerateAnswerUtils.java
- libraries/bot-ai-qna/src/main/java/com/microsoft/bot/ai/qna/utils/QnACardBuilder.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerRecognizerTests.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTraceInfoTests.java
> [Double Brace] Remove double braces in bot-ai-qna

- libraries/bot-azure/src/main/java/com/microsoft/bot/azure/CosmosDbPartitionedStorage.java
- libraries/bot-azure/src/test/java/com/microsoft/bot/azure/CosmosDbPartitionStorageTests.java
…CsosmosDbPartitionedStorage
Fixes #
- 
-
-
> [SDK][Azure] Remove double brace in azure library code + test

- libraries/bot-applicationinsights/pom.xml
- libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/AvailabilityTelemetry.java
- libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/BotTelemetryClientImpl.java
- libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/core/TelemetryInitializerMiddleware.java
- libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/core/package-info.java
- libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/package-info.java
- libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/BotTelemetryClientTests.java
- libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/TelemetryInitializerTests.java
- libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/TelemetryWaterfallTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/ComponentDialogTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/DialogSetTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/WaterfallTests.java
> [SDK][Application-Insights] Fix migration errors

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/BotFrameworkAdapter.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/BotState.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/MessageFactory.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/ShowTypingMiddleware.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/TelemetryLoggerMiddleware.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/TranscriptLoggerMiddleware.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/TurnContextImpl.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/ActivityHandlerTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/AutoSaveStateMiddlewareTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/BotAdapterTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/BotFrameworkAdapterTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/InspectionTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/MemoryConversations.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/MessageFactoryTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/StorageBaseTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TelemetryMiddlewareTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TestAdapterTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TestMessage.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TestUtilities.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TranscriptMiddlewareTest.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TurnContextTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/adapters/TestAdapter.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/teams/TeamsActivityHandlerBadRequestTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/teams/TeamsActivityHandlerHidingTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/teams/TeamsActivityHandlerNotImplementedTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/teams/TeamsActivityHandlerTests.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/teams/TeamsInfoTests.java
…botbuilder library
Fixes #
- 
-
-
> [SDK][BotBuilder] Remove double brace in botbuilder library code + test

- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/DialogContext.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/Recognizer.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/choices/ChoiceFactory.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/choices/ChoiceRecognizers.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/choices/Find.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/prompts/ChoicePrompt.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/prompts/ConfirmPrompt.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/prompts/OAuthPrompt.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/ObjectPathTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/choices/ChoicesChannelTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/choices/ChoicesRecognizerTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/prompts/ActivityPromptTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/prompts/ChoicePromptTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/prompts/NumberPromptTests.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/prompts/OAuthPromptTests.java
…botbuilder-dialogs library
Fixes #
- 
-
-
> [SDK][BotBuilder-Dialogs] Remove double brace in botbuilder-dialogs library code + test

- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/AdapterWithErrorHandler.java
> [SDK][Bot-Integration-Core] Remove double brace in bot-integration-core library code + test

- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/Activity.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/AnimationCard.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/Attachment.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/AudioCard.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/CardAction.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ChannelAccount.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ConversationAccount.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ConversationReference.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/Entity.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/HeroCard.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/MessageReaction.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/OAuthCard.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ReceiptCard.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/SigninCard.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/SuggestedActions.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/ThumbnailCard.java
- libraries/bot-schema/src/main/java/com/microsoft/bot/schema/VideoCard.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/ActivityTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/AnimationCardTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/AudioCardTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/EntitySchemaValidationTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/HeroCardTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/OAuthCardTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/ReceiptCardTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/SigninCardTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/ThumbnailCardTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/VideoCardTest.java
- libraries/bot-schema/src/test/java/com/microsoft/bot/schema/teams/MessageActionsPayloadTest.java
> [SDK][BotBuilder-Schema] Remove double brace in botbuilder-schema library code + test

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ChannelValidation.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/EmulatorValidation.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/EnterpriseChannelValidation.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/GovernmentChannelValidation.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/RetryParams.java
- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/AllowedCallersClaimsValidationTests.java
- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/AttachmentsTest.java
- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/ConversationsTest.java
- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/JwtTokenExtractorTests.java
- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/JwtTokenValidationTests.java
- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/RetryTests.java
> [SDK][Bot-Connector] Remove double brace initializations in code + unit tests

- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/choices/ChoiceFactoryTests.java
> [BotBuilder-Dialogs] - Remove DBI

- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/JwtTokenValidationTests.java
> [Double Brace][Connector] Add missing DBI in connector

- libraries/bot-ai-qna/src/test/java/com/microsoft/bot/ai/qna/QnAMakerTests.java
> [QnA] Remove DBI in QnAMakerTests

- Generator/generator-botbuilder-java/generators/app/templates/core/src/main/java/DateResolverDialog.java
- Generator/generator-botbuilder-java/generators/app/templates/core/src/main/java/FlightBookingRecognizer.java
- samples/13.core-bot/src/main/java/com/microsoft/bot/sample/core/FlightBookingRecognizer.java
> [Double Brace] Fix DBIs in core bot and generator sample

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/BotFrameworkAdapter.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/TelemetryMiddlewareTests.java
> [SDK] Fix remaining DBI in bot-builder library

- samples/21.core-bot-app-insights/src/main/resources/cards/welcomeCard.json
> [Samples][21.corebot-app-insights] Copy cards folder

- samples/21.core-bot-app-insights/src/main/resources/application.properties
> [Samples][Corebot-Application-Insights] Add application.properties file

- samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/DialogAndWelcomeBot.java
> [Samples][21.corebot-app-insights] Migrate DialogAndWelcomeBot class

- samples/21.core-bot-app-insights/src/main/webapp/META-INF/MANIFEST.MF
- samples/21.core-bot-app-insights/src/main/webapp/WEB-INF/web.xml
- samples/21.core-bot-app-insights/src/main/webapp/index.html
> [Samples][21.corebot-app-insights] Migrate wwwroot folder

- samples/21.core-bot-app-insights/README-LUIS.md
- samples/21.core-bot-app-insights/README.md
> [Samples][21.corebot-app-insights] Migrate READMEs documents

- samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/MainDialog.java
> [Samples][CoreBot-App-Insights] Add MainDialog class

- samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/BookingDetails.java
> [Samples][Corebot-App-Insights] Add BookingDetails class

- samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/DateResolverDialog.java
> [Samples][21.corebot-app-insights] Migrate DateResolverDialog class

- samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/DialogBot.java
> [Samples][21.corebot-app-insights] Migrate DialogBot class

- samples/14.nlp-with-dispatch/src/main/webapp/index.html
> [Samples][nlp-with-dispatch] Migrate wwwroot folder

- samples/14.nlp-with-dispatch/deploymentTemplates/template-with-new-rg.json
- samples/14.nlp-with-dispatch/deploymentTemplates/template-with-preexisting-rg.json
> [Samples][nlp-with-dispatch] Migrate deployment templates folder

- samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/FlightBookingRecognizer.java
> [Samples][Corebot-App-Insights] Add FlightBookingRecognizer class

- samples/14.nlp-with-dispatch/src/main/resources/application.properties
> [Samples][nlp-with-dispatch] Add properties in application.properties file

- samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/AdapterWithErrorHandler.java
> [Samples][21.corebot-app-insights] Add internal AdapterWithErrorHandler

- samples/21.core-bot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/Application.java
> [Sample 21] Add Application.java

- samples/14.nlp-with-dispatch/src/main/java/com/microsoft/bot/sample/nlp/with/dispatch/Application.java
> [Samples][nlp-with-dispatch] Migrate startup class as Application class

- samples/14.nlp-with-dispatch/src/main/java/com/microsoft/bot/sample/nlp/with/dispatch/BotServices.java
> [Samples][nlp-with-dispatch] Migrate BotServices interface

- samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/FlightBookingRecognizer.java
- samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/MainDialog.java
- samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/package-info.java
> [Samples][Corebot-App-Insights] Add package-info + some checkstyle fixes

- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHostAdapter.java
> [Samples][42.scaleout] Add DialogHostAdapter class

- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/RefAccessor.java
> [Samples][42.scaleout] Add RefAccessor class

- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHost.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/Store.java
> [Samples][42.scaleout] Add DialogHost and change of Object to JsonNode

- samples/40.timex-resolution/pom.xml
- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Parsing.java
> [Samples][40.timex-resolution] Migrate Parsing class and fix pom

- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Constraints.java
> [Samples][Timex-Resolution] Add Constraints class

- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/ScaleoutBot.java
> [Samples][42.scaleout] Add ScaleoutBot class

- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/MemoryStore.java
> [Samples][42.scaleout] Add MemoryStore class

- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Ambiguity.java
> Migrate Ambiguity class

- libraries/bot-ai-luis-v3/src/main/java/com/microsoft/bot/ai/luis/LuisRecognizerOptionsV3.java
- libraries/bot-applicationinsights/pom.xml
- libraries/bot-applicationinsights/src/main/java/com/microsoft/bot/applicationinsights/ApplicationInsightsBotTelemetryClient.java
- libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/BotTelemetryClientTests.java
- libraries/bot-applicationinsights/src/test/java/com/microsoft/bot/applicationinsights/MyBotTelemetryClient.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/TelemetryLoggerMiddleware.java
- samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/AdapterWithErrorHandler.java
- samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/Application.java
- samples/21.corebot-app-insights/src/main/java/com/microsoft/bot/sample/corebot/app/insights/BookingDialog.java
> [Samples][21.core-bot-app-insights] Fix migrated sample

- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Ranges.java
> [Samples][Timex Resolution] Add Ranges class

- samples/42.scaleout/pom.xml
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/BlobStore.java
> [Samples][42.scaleout] Add BlobStore class

- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/Application.java
> [Samples][42.scaleout] Add Application class

- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Application.java
- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Resolutions.java
> [Samples][timex-resolution] Add Resolutions class

- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/LanguageGeneration.java
> [Samples][40.timex-resolution] Migrate LanguageGeneration class

- samples/40.timex-resolution/README.md
> [Samples][40.timex-resolution] Migrate README document

- libraries/bot-dialogs/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedDateTimeParser.java
- libraries/bot-dialogs/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimexUtility.java
- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Ambiguity.java
- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Application.java
- samples/40.timex-resolution/src/main/java/com/microsoft/bot/sample/timex/resolution/Ranges.java
> [Samples][Timex Resolution] Fixes

- samples/42.scaleout/pom.xml
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/Application.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/BlobStore.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHost.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHostAdapter.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/MemoryStore.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/RefAccessor.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/RootDialog.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/ScaleoutBot.java
- samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/Store.java
> [Samples][42.scaleout] Fix migration issues

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/CloudAdapterBase.java
> [BotBuilder] Migrate CloudAdapterBase

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/AuthenticateRequestResult.java
> [Bot-Connector] Add AuthenticateRequestResult class

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/BotFrameworkAuthenticationFactory.java
> [Bot-Connector] Add BotFrameworkAuthenticationFactory class

- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/ConfigurationBotFrameworkAuthentication.java
> Add ConfigurationBotFrameworkAuthentication class

- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/CloudAdapter.java
> Add CloudAdapter class

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/DelegatingCredentialProvider.java
> Add DelegatingCredentialProvider class

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/PasswordServiceClientCredentialFactory.java
> [Bot-Connector] Add PasswordServiceClientCredentialFactory

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/UserTokenClientImpl.java
> [Bot-Connector] Add UserTokenClientImpl

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/AuthenticationConstants.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ClaimsIdentity.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ParameterizedBotFrameworkAuthentication.java
> Add ParameterizedBotFrameworkAuthentication class

- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/ConfigurationServiceClientCredentialFactory.java
> Add class ConfigurationServiceClientCredentialFactory

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ConnectorFactoryImpl.java
> Add ConnectorFactoryImpl class

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/CloudChannelServiceHandler.java
> Add CloudChannelServiceHandler class

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/ChannelServiceHandlerBase.java
> [Bot-Builder] Add ChannelServiceHandlerBase

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/skills/SkillHandlerImpl.java
> [Bot-Builder] Add SkillHandlerImpl

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/BotFrameworkClientImpl.java
> Add BotFrameworkClientImpl class

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/skills/CloudSkillHandler.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/skills/CloudSkillHanlder.java
> Add CloudSkillHandler class

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/BotFrameworkClientImpl.java
> Remove null checks for fromBotId and toBotId

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/skills/SkillHandler.java
> [Bot-Builder] Update SkillHandler

- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/PasswordServiceClientCredentialFactoryTests.java
> [Bot-Connector] Add PasswordServiceClientCredentialFactoryTests

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/BotFrameworkAuthenticationFactory.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/BotFrameworkClientImpl.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ParameterizedBotFrameworkAuthentication.java
- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/BotFrameworkAuthenticationTests.java
> [Bot-Connector] Add BotFrameworkAuthenticationTests

- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/CloudChannelServiceHandlerTests.java
> Add CloudChannelServiceHandlerTests class

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/OAuthConfiguration.java
> [Bot-Connector] Add validateAuthority in OAuthConfiguration

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/BotAdapter.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/CloudAdapterBase.java
> [Bot-Builder] Set the correct Audience claim

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/AppCredentials.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/PasswordServiceClientCredentialFactory.java
> Add CloudAdapter changes in AppCredentials class

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/CertificateAppCredentials.java
> Update CertificateAppCredentials class

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/ChannelServiceHandler.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/CloudAdapterBase.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/skills/SkillHandler.java
- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/skills/SkillHandlerImpl.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/CertificateAppCredentials.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ConnectorFactoryImpl.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/OAuthConfiguration.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ParameterizedBotFrameworkAuthentication.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/PasswordServiceClientCredentialFactory.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/restclient/ServiceResponseBuilder.java
- libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/SkillDialogOptions.java
- libraries/bot-dialogs/src/test/java/com/microsoft/bot/dialogs/SkillDialogTests.java
- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/BotFrameworkHttpClient.java
- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/CloudAdapter.java
- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/ConfigurationBotFrameworkAuthentication.java
- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/ConfigurationServiceClientCredentialFactory.java
- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/SkillHttpClient.java
- libraries/bot-integration-core/src/test/java/com/microsoft/bot/integration/CloudAdapterTests.java
> Fix PMD/Build issues

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/ParameterizedBotFrameworkAuthentication.java
> [bot-builder] Fix broken unit tests of CloudChannelServiceHandlerTests

- libraries/bot-builder/src/main/java/com/microsoft/bot/builder/skills/SkillHandlerImpl.java
- libraries/bot-builder/src/test/java/com/microsoft/bot/builder/CloudSkillHandlerTests.java
> Fix CloudSkillHandlerTests

- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/BotFrameworkAuthenticationFactory.java
- libraries/bot-connector/src/main/java/com/microsoft/bot/connector/authentication/BotFrameworkClientImpl.java
- libraries/bot-connector/src/test/java/com/microsoft/bot/connector/BotFrameworkAuthenticationTests.java
> [#1222] Fix broken unit tests of BotFrameworkAuthenticationTests

- libraries/bot-integration-core/src/main/java/com/microsoft/bot/integration/CloudAdapterWithErrorHandler.java
> Add CloudAdapterWithErrorHandler class

- libraries/bot-integration-spring/src/main/java/com/microsoft/bot/integration/spring/BotDependencyConfiguration.java
> Create getCloudAdapter() method to consume the CloudAdapter
